import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Plus, Search, ChevronLeft, ChevronRight, RefreshCw, Filter } from "lucide-react";
import { toast } from "sonner";
import DrawerForm from "./DrawerForm";
import { useAuth } from "../auth/AuthProvider";
import { CustomersApi } from "../data/db";

const STATUSES = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "archived", label: "Archived" },
];

const FIELDS = [
  { key: "name", label: "Company name", required: true, span: 2 },
  { key: "code", label: "Customer code", placeholder: "AUTO-generated by you (e.g. CUS-0028)" },
  { key: "industry", label: "Industry", placeholder: "Automotive, hydraulics..." },
  { key: "gstin", label: "GSTIN" },
  { key: "legal_name", label: "Legal name" },
  { key: "phone", label: "Phone" },
  { key: "email", label: "Email", type: "email" },
  { key: "website", label: "Website" },
  { key: "city", label: "City" },
  { key: "state", label: "State" },
  { key: "country", label: "Country" },
  { key: "postal_code", label: "Postal code" },
  { key: "payment_terms", label: "Payment terms", placeholder: "Net 30" },
  { key: "status", label: "Status", options: STATUSES, required: true },
  { key: "address_line1", label: "Address", span: 2 },
  { key: "notes", label: "Notes", textarea: true, span: 2 },
];

const PAGE_SIZE = 10;

export default function CustomersModule() {
  const { activeOrgId } = useAuth();
  const [rows, setRows] = useState([]);
  const [count, setCount] = useState(0);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(false);
  const [editing, setEditing] = useState(null); // null = closed, {} = new, {..} = edit

  const load = useCallback(async () => {
    if (!activeOrgId) return;
    setLoading(true);
    try {
      const res = await CustomersApi.list(activeOrgId, { search, status: status || undefined, page, pageSize: PAGE_SIZE });
      setRows(res.rows); setCount(res.count);
    } catch (e) { toast.error(e.message); }
    finally { setLoading(false); }
  }, [activeOrgId, search, status, page]);

  useEffect(() => { load(); }, [load]);

  async function save(payload) {
    if (payload.id) { await CustomersApi.update(payload.id, stripMeta(payload)); toast.success("Customer updated"); }
    else { await CustomersApi.create(activeOrgId, stripMeta(payload)); toast.success("Customer created"); }
    setEditing(null); load();
  }
  async function remove(rec) { await CustomersApi.remove(rec.id); toast.success("Customer deleted"); setEditing(null); load(); }

  const pages = Math.max(1, Math.ceil(count / PAGE_SIZE));

  return (
    <div className="module-view">
      <div className="page-title">
        <div>
          <div className="eyebrow">Precise Industries / Customers</div>
          <h1 data-testid="module-title">Customers</h1>
          <p>Every customer, contact and account — connected to Supabase.</p>
        </div>
        <button className="primary-btn" data-testid="create-customer-button" onClick={() => setEditing({ status: "active", country: "India" })}><Plus size={16}/> New customer</button>
      </div>
      <div className="module-toolbar">
        <div className="search-field small">
          <Search size={16}/>
          <input data-testid="customers-search" placeholder="Search by name, GSTIN, city, email..." value={search} onChange={e => { setPage(1); setSearch(e.target.value); }}/>
        </div>
        <div className="search-field small filter-select">
          <Filter size={14}/>
          <select data-testid="customers-status-filter" value={status} onChange={e => { setPage(1); setStatus(e.target.value); }}>
            <option value="">All statuses</option>
            {STATUSES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}
          </select>
        </div>
        <button className="filter-btn" data-testid="customers-refresh" onClick={load}><RefreshCw size={13}/> Refresh</button>
        <span className="toolbar-count" data-testid="customers-count">{count} customer{count === 1 ? "" : "s"}</span>
      </div>
      <section className="panel table-panel">
        <div className="table-scroll">
          <table data-testid="customers-table">
            <thead><tr><th>Name</th><th>Code</th><th>Industry</th><th>City</th><th>GSTIN</th><th>Status</th><th></th></tr></thead>
            <tbody>
              {loading && rows.length === 0 && <tr><td colSpan={7} className="loading-cell">Loading customers…</td></tr>}
              {!loading && rows.length === 0 && (
                <tr><td colSpan={7} className="empty-cell">
                  <b>No customers yet</b>
                  <small>Add your first customer to start creating quotes and jobs.</small>
                </td></tr>
              )}
              {rows.map((r, i) => (
                <tr key={r.id} data-testid={`customer-row-${i}`}>
                  <td><b>{r.name}</b><small>{r.legal_name || "—"}</small></td>
                  <td>{r.code || "—"}</td>
                  <td>{r.industry || "—"}</td>
                  <td>{r.city || "—"}</td>
                  <td>{r.gstin || "—"}</td>
                  <td><span className={`badge ${r.status}`}>{r.status}</span></td>
                  <td><button className="outline-btn" data-testid={`customer-edit-${i}`} onClick={() => setEditing(r)}>Edit</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <Pagination page={page} pages={pages} onPrev={() => setPage(p => Math.max(1, p - 1))} onNext={() => setPage(p => Math.min(pages, p + 1))} count={count} pageSize={PAGE_SIZE}/>
      </section>

      {editing && (
        <DrawerForm
          title={editing?.id ? `Edit ${editing.name}` : "New customer"}
          record={editing}
          fields={FIELDS}
          onSave={save}
          onDelete={remove}
          onClose={() => setEditing(null)}
          testidPrefix="customer"
        />
      )}
    </div>
  );
}

export function Pagination({ page, pages, onPrev, onNext, count, pageSize }) {
  const from = count === 0 ? 0 : (page - 1) * pageSize + 1;
  const to = Math.min(count, page * pageSize);
  return (
    <div className="pagination">
      <span data-testid="pagination-info">Showing {from}–{to} of {count}</span>
      <button className="icon-btn" data-testid="pagination-previous" disabled={page <= 1} onClick={onPrev}><ChevronLeft size={16}/></button>
      <span className="page-indicator">{page} / {pages}</span>
      <button className="icon-btn" data-testid="pagination-next" disabled={page >= pages} onClick={onNext}><ChevronRight size={16}/></button>
    </div>
  );
}

function stripMeta(obj) {
  const { id, organization_id, created_at, updated_at, created_by, updated_by, ...rest } = obj;
  return rest;
}
